---


- name: install dependencies for scripts
  apt: name={{ item }}
  with_items:
    - "{{ scripts_pkgs }}"
  tags:
    - scripts

#- name: remove obsolete scripts
#  file: name=/root/{{ item }} state=absent
#  with_items:
#    - moveUsers
#    - copyOver
#    - copyAndMove
#  tags:
#    - scripts

- name: install scripts
  template: src={{ item.name }}.j2 dest={{ item.path }}/{{ item.name }} mode={{ item.mode }}
  with_items:
    - "{{ scripts }}"
  tags:
    - scripts

- name: sudoers
  copy: src=sudo-scanFiles dest=/etc/sudoers.d/91-scanFiles mode=0440
  tags:
    - scripts

