---

- name: install packages
  apt:  name={{item}} 
        state=installed
        update_cache={{apt_config.update_cache}}
        cache_valid_time={{apt_config.cache_valid_time}}
  with_items:
    - libpython2.7
    - socat

- name: install haproxy script for collectd
  copy:
     src=collectd-haproxy/haproxy.py
     dest=/opt/collectd/collectd.plugins/haproxy.py
  notify: restart collectd
  tags:
    - collectd

- name: drop collectd config for haproxy
  template:
     src=collectd_haproxy.conf.j2
     dest=/etc/collectd/collectd.conf.d/collectd_haproxy.conf
  notify: restart collectd
  tags:
    - config
    - collectd
    

