---

- name: install nagios
  apt: 
    pkg={{ item }}
    state=present
    update_cache={{apt_config.update_cache}}
    cache_valid_time={{apt_config.cache_valid_time}}
  with_items:
   - nagios-plugins
   #- ruby
   - libnagios-plugin-perl
   - libwww-perl
   - libdata-dumper-simple-perl
  tags: nagios

