---

- name: install s3 backup
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"
  with_items:
    - s3cmd
  tags:
    - ldap_backup

- name: install s3backup script
  template:
    src: "ldap_backup.sh"
    dest: "/root/ldap_backup.sh"
    mode: "0500"
    owner: "root"
  tags:
    - ldap_backup

- name: install s3backup cronjobs
  cron:
    cron_file: "ldap_backup"
    hour: "4"
    minute: "36"
    name: "backup ldap"
    state: "present"
    user: "root"
    job: "/root/ldap_backup.sh"
  tags:
    - ldap_backup
    - cron
