#!/usr/bin/env bash

BASEDIR=`dirname $0`
if [ -e "$BASEDIR/setup" ]; then
   . "$BASEDIR/setup" 
else 
   . "$BASEDIR/setup.sample"
fi

. "$BASEDIR/$NAME_PREFIX.env" 


###########
SCRIPTNAME=`basename $0`
REGION="$OS_REGION_NAME"

BACKBONE_4_PREFIX_VAR="backbonePrefix_4"
BACKBONE_4_PREFIX=${!BACKBONE_4_PREFIX_VAR}
BACKBONE_6_PREFIX_VAR="backbonePrefix_6"
BACKBONE_6_PREFIX=${!BACKBONE_6_PREFIX_VAR}
DRIVE_PREFIX_VAR="drivePrefix_4"
DRIVE_PREFIX=${!DRIVE_PREFIX_VAR}


STACK_PARAMS_COMMON="name_prefix=$NAME_PREFIX;region=$REGION"
STACK_PARAMS_NETWORK="$STACK_PARAMS_COMMON;cidr=${DRIVE_PREFIX}0/24;gateway_ip=${DRIVE_PREFIX}1;pool_start=${DRIVE_PREFIX}240;pool_end=${DRIVE_PREFIX}254"
STACK_PARAMS="$STACK_PARAMS_COMMON;ssh_key=$SSH_KEY"

TEMPL_DIR=${BASEDIR}/templates
RSC_DIR=${BASEDIR}/resources

HEAT=heat
OPENSTACK=openstack
NEUTRON=neutron
GIT=git
