---

- apt: name=apache2 update_cache=yes
- apt: name=libapache2-mod-php5
- apt: name=php5-fpm
#- apache2_module: state=present name=ssl
#- apache2_module: state=present name=default-ssl
- apache2_module: state=present name=rewrite
- apache2_module: state=present name=headers
- apache2_module: state=present name=env
- apache2_module: state=present name=dir
- apache2_module: state=present name=mime
- apache2_module: state=present name=php5

- copy: src=files/apache_owncloud.conf dest=/etc/apache2/conf-available/owncloud.conf mode=0644 owner=root group=root
- file: path=/etc/apache2/conf-enabled/owncloud.conf src=/etc/apache2/conf-available/owncloud.conf state=link owner=root group=root
- file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
- service: name=apache2 state=started
    