---

- name: add owncloud logrotation config file
  template:
    src=logrotate.d/{{item}}
    dest=/etc/logrotate.d/{{item}}
    mode=0644 owner=root
  with_items:
    - owncloud
    - php-fpm
  tags:
    - app
    - config
    - logrotate

- name: make sure that logrotate is configured to run hourly
  shell: 
    dpkg-divert --add --rename --divert /etc/cron.hourly/logrotate /etc/cron.daily/logrotate
  tags:
    - app
    - config
    - logrotate
