---

- name: Create dirs
  file: path="{{item}}" state=directory group=root owner=root
  with_items:
    - "/etc/owncloud/"
    - "/var/log/php/"
    - "/var/run/php"
  tags:
    - ocphp_fpm


- include: install_php_fpm_config.yml
  with_items: "{{shard_mapping[service_name]}}"
  loop_control:
    loop_var: shards

- include: install_occonfig.yml
  with_items: "{{shard_config[service_name]}}"
  loop_control:
    loop_var: shards

- name: ocphp_fpm docker
  docker_container:
    name: "php_fpm_{{item.oc_major_version}}.{{item.oc_minor_version}}"
    image: "{{ocphp_fpm_docker_name}}:{{item.oc_major_version}}.{{item.oc_minor_version}}-{{item.oc_image_version}}"
    network_mode: host
    restart_policy: "unless-stopped"
    state: "started"
    pull: "{{ docker_pull }}"
    env:
       SHARDS: '{{item.shards | join(" ")}}'
    volumes:
      - "/etc/owncloud:/etc/owncloud"
      - "{{owncloud_logdir}}:/var/log/owncloud"
      - "/var/log/php:/var/log"
      - "/run/mysqld:/run/mysqld"
      - "/mnt:/mnt"
      - "/var/run/php:/var/run/php"
      - "/run/shm:/tmp"
      - "{{owncloud_webroot}}:{{owncloud_webroot}}"
    #command: "bash -c 'sleep 3000'"
  with_items:
    - "{{shard_mapping[service_name]}}"
  tags:
    - ocphp_fpm
    - ocphp_fpm_container
