heat_template_version: 2013-05-23

description: |
  This template adds a floating ip.

parameters:
  name_prefix:
    type: string
    description: "Resources Name Prefix"
  region:
    type: string
    label: "SWITCHengines region: LS or ZH"
    default: "ZH"  
  cidr:
    type: string
    default: "not used"
  gateway_ip:
    type: string
    default: "not used"
  pool_start:
    type: string
    default: "not used"
  pool_end:
    type: string
    default: "not used"

resources:
  external_network:
    type: types/external_network.yaml
    properties:
      region: { get_param: region }
  public_ipv4:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_attr: [external_network, network_id] }

outputs:
  floating_ip_address:
    value:  { get_attr: [public_ipv4, ip]}
  floating_ip_id:
    value:  { get_resource: public_ipv4 }
      