---

# deletion
- include: server.yml
  when: os_action == "delete"
- include: port.yml
  when: os_action == "delete"
- include: volume.yml
  when: os_action == "delete"
- include: data_volume.yml
  when: os_action == "delete"
- include: network.yml
  when: os_action == "delete"

# creation
- include: network.yml
  when: os_action == "create"
- include: security_group.yml
  when: os_action == "create"
- include: server_group.yml
  when: os_action == "create"
- include: volume.yml
  when: os_action == "create"
- include: port.yml
  when: os_action == "create"
- include: server.yml
  when: os_action == "create"
- include: data_volumes.yml
  when: os_action == "create"
- include: vip.yml
  when: os_action == "create"
