---

# deletion
- include: server.yml
  when: os_action == "delete"
- include: port.yml
  when: os_action == "delete"
- include: volume.yml
  when: os_action == "delete"

# creation
- include: server_group.yml
  when: os_action == "create"
- include: volume.yml
  when: os_action == "create"
- include: port.yml
  when: os_action == "create"
- include: server.yml
  when: os_action == "create"
- include: vip.yml
  when: os_action == "create"
