---

- name: "{{ os_action }} a network"
  os_network:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}"
    timeout: 200
  with_items: "{{ os_network }}"
  tags:
    - os_network

- name: "{{ os_action }} a subnet"
  os_subnet:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}_ipv4"
    network_name: "{{ item.name }}"
    cidr: "{{ item.cidr }}"
    timeout: 200
  with_items: "{{ os_network }}"
  tags:
    - os_network

- name: "{{ os_action }} a router"
  os_router:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}_router"
    network: "public"
    interfaces: "{{ item.name }}_ipv4"
    timeout: 200
  with_items: "{{ os_network }}"
  tags:
    - os_network
    - os_router
