---

- name: install server groups
  os_server_group:
    state: present
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}"
    policies: "{{ item.policies }}"
  with_items: "{{ os_server_group['list'] }}"
  tags:
    - os_server_group
