---

- name: install server groups
  os_server_group:
    state: present
    auth:
      auth_url: "{{ os_auth_url }}"
      username: "{{ os_username }}"
      password: "{{ os_password }}"
      project_name: "{{ os_tenant }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}"
    policies: "{{ item.policies }}"
  with_items: "{{ os_server_group[site]['list'] }}"
  tags:
    - os_server_group

