---

- name: Create a port with a static VIP
  os_port:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    state: present
    name: "{{ item.name }}"
    network: "{{ os_network[site] }}"
    fixed_ips:
      - ip_address: "{{ item.ip }}"
  with_items:
    - "{{ os_vip['ips'] }}"
  tags:
    - os_vip

- name: Make VIP ip assignable to vm-ports
  os_port:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    state: present
    network: "{{ os_network[site] }}"
    name: "{{ item.name }}"
    allowed_address_pairs: "{{ item.ips }}"
  with_items:
    - "{{ os_vip['ports'] }}"
  tags:
    - os_vip


