---

- name: "{{ os_action }} a root volume"
  os_volume:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    state: "{{ os_volume_state }}"
    size: "{{ os_server[site][item].root_size }}"
    display_name: "{{ os_server[site][item].name }}_root"
    image: "{{ os_server[site][item].image }}"
  with_items: "{{ server_list }}"
  when: server != ""
  tags:
    - os_volume

