---
- name: Add nginx apt key
  apt_key:
    url='http://nginx.org/keys/nginx_signing.key'
  when: ansible_os_family == 'Debian'

- name: Add nginx apt repo
  apt_repository:
    repo="deb http://nginx.org/packages/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename }} nginx"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  
- name: Install Nginx apt package
  apt: pkg=nginx state=latest
    update_cache={{apt_config.update_cache}} cache_valid_time={{apt_config.cache_valid_time}}
  when: ansible_os_family == 'Debian'

- name: Disable default servers
  file:
    path=/etc/nginx/conf.d/{{ item.path }}
    state=absent
  with_items:
    - { path: 'default.conf' }
    - { path: 'example_ssl.conf' }

- name: Make monit to look after nginx
  template:
    src=monitor/nginx.monitrc.conf.j2
    dest=/etc/monit/conf.d/nginx.monitrc.conf
    owner=root group=root mode=644
  notify: Restart monit
  tags:
    - config
  