---

- name: "restart ocphp_fpm"
  shell: "docker restart php_fpm_{{item.oc_major_version}}.{{item.oc_minor_version}}; docker restart ocapache"
  with_items:
    - "{{shard_mapping[service_name]}}"
  


