---

- name: prometheus docker
  docker_container:
    name: mysqld-exporter
    image: "prom/mysqld-exporter:{{mysqld_exporter_version}}"
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    pull: true
    ports:
      - "9104:9104"
    env:
      DATA_SOURCE_NAME: "root:{{mariadb_passwd}}@(localhost:3306)/"
    command: "-collect.binlog_size=true -collect.info_schema.processlist=true -collect.info_schema.query_response_time=true -collect.info_schema.tables=true -collect.info_schema.tablestats=true -collect.auto_increment.columns=true -collect.info_schema.userstats=true"
  become: true
  tags:
    - prometheus
    - mysqld_exporter
