---

- name: prometheus docker
  docker_container:
    name: node-exporter
    #image: "prom/node-exporter:{{node_exporter_version}}"
    image: "prom/node-exporter"
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    pull: true
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    command: '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc|rootfs/sys|rootfs/var|rootfs/dev|rootfs/var|rootfs/proc|rootfs/run|)($|/)"'
  become: true
  tags:
    - prometheus
    - node_exporter
