---

- name: prometheus docker 
  docker:
    name: node-exporter
    image: "prom/node-exporter:{{node_exporter_version}}"
    state: reloaded
    pull: always
    net: host
    ports: 
      - "9100:9100"
    restart_policy: always
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    command: '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc|rootfs/sys|rootfs/var|rootfs/dev|rootfs/var|rootfs/proc|rootfs/run|)($|/)"'
  become: true
  tags:
    - prometheus
    - node_exporter

