---

- name: ensure packages are installed
  action: apt name={{item}} 
    update_cache={{apt_config.update_cache}} cache_valid_time={{apt_config.cache_valid_time}}
  with_items:
    - git
    - python-pip
    - libxml2-utils
  tags:
    - smashbox

- name: clone smashbox.git
  git: repo=https://github.com/switch-ch/smashbox.git dest=/home/ubuntu/smashbox
  become_user: ubuntu
  tags:
    - smashbox

- name: clone pyocclient.git
  git: repo=https://github.com/owncloud/pyocclient.git dest=/home/ubuntu/pyocclient
  become_user: ubuntu
  tags:
    - smashbox

- name: install config
  template: src=smashbox.conf.j2 dest=/home/ubuntu/smashbox/etc/smashbox.conf owner=ubuntu group=ubuntu
  tags:
    - smashbox

- name: set PYTHONPATH
  lineinfile: dest=/etc/environment regexp="^export PYTHONPATH.*" line="export PYTHONPATH=/home/ubuntu/pyocclient"
  tags:
    - smashbox

- name: pip install
  pip: name=requests
  tags:
    - smashbox



