---

- name: copy ocphp_fpm build instructions to remote host
  synchronize:
    src: ocphp_fpm
    dest: /tmp
    delete: yes
  tags:
    - ocphp_fpm

- name: Create dirs
  file: path="{{item}}" state=directory owner=root
  with_items:
    - "/tmp/ocphp_fpm/patches/masterpasswd/apps/user_ldap"
  tags:
    - ocphp_fpm


- name: copy ocphp_fpm configs to remote host
  template:
    src={{item.name}}
    dest=/tmp/ocphp_fpm/{{item.dest}}
    mode={{item.mode}}
  with_items:
    - { name: "{{owncloud_fork_name}}.{{owncloud_major_version}}.dockerfile", dest: "Dockerfile", mode: "0644" }
    - { name: "{{owncloud_fork_name}}.entrypoint.sh", dest: "entrypoint.sh", mode: "0755" }
    - { name: "user.ini", dest: "user.ini", mode: "0644" }
    - { name: "patches/masterpasswd/apps/user_ldap/user_ldap.php", dest: "patches/masterpasswd/apps/user_ldap/user_ldap.php", mode: "0644" }
    - { name: "patches/masterpasswd/apps/user_ldap/User_LDAP.10.0.php", dest: "patches/masterpasswd/apps/user_ldap/User_LDAP.10.0.php", mode: "0644" }
  tags:
    - ocphp_fpm


- name: build ocphp_fpm
  docker_image:
    path: "/tmp/ocphp_fpm"
    name: "{{ocphp_fpm_docker_name}}"
    tag: "{{ocphp_fpm_docker_tag}}"
    dockerfile: "Dockerfile"
    state: present
    tls_hostname: localhost
    force: true
    pull: "{{ docker_pull }}"
    nocache: "{{ no_docker_cache }}"
  tags:
    - ocphp_fpm

- name: push ocphp_fpm image
  shell: docker push "{{ocphp_fpm_docker_image}}"
  tags:
    - ocphp_fpm
