---

# Performs a rolling dist upgrade on all app servers and then reboots them
# Change the value of serial: to adjust the number of server to be updated.


- hosts: 
    - web
    - sync
    - dev
    - mgmt
    - nfs
    - db
    - redis
    - ldap
    - lb
    #- jumphost
  #serial: 1
  become: yes
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get dist-upgrade
      apt: upgrade=dist dpkg_options='force-confold,force-confdef'

    - name: reboot
      command: '/sbin/reboot'
      async: 0
      poll: 0
      ignore_errors: true




