---

- hosts: 
    - web
    - sync
    - dev
    - mgmt
  become: yes
  tasks:
    - name: restart ocphp_fpm
      shell: "docker restart php_fpm_{{ssd[site].major_version}}.{{ssd[site].minor_version}}"



