---

- name: Copy maxscale configuration to /etc
  template:
      src={{item}}.j2
      dest=/etc/{{item}}
      mode=0644 owner=root group=root
  notify:
    - restart maxscale
  with_items:
    - maxscale.cnf
  tags: maxscale


- name: 'Create directory for MariaDB socket'
  file: path=/run/mysqld state=directory owner=997 group=996 mode=0755
  tags: maxscale


- name: maxscale docker
  docker_container:
    name: maxscale
    image: "{{maxscale_docker_image}}"
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    pull: true
    volumes:
      - "/etc/maxscale.cnf:/etc/maxscale.cnf"
      - "/run/mysqld:/run/mysqld"
      - "/run/systemd/journal/syslog:/dev/log"
  tags:
    - maxscale
