---

- name: create directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ snapshot_user_name }}"
  with_items:
    - /home/{{ snapshot_user_name }}/bin
    - /var/log/drive
  tags:
    - scripts

- name: create log directory
  file: path=/var/log/drive state=directory mode=0755 owner={{ snapshot_user_name }}

- name: install snapshot cronjobs
  cron: cron_file=SWITCHdrive
    hour=1 minute=0
    name="backup data disks"
    state=present
    user={{ snapshot_user_name }}
    job="/home/{{ snapshot_user_name }}/bin/manageSnapshots.py >> /var/log/drive/backup.log"
  tags:
    - config
    - cron
