---

- name: set root password
  user: 
     name=root
     password={{enc_root_passwd}}
  tags: 
    - common
    - users

- name: Delete users
  user:
    name={{ item }}
    state=absent
    remove=yes
  with_flattened: '{{remove_users}}'
  tags: 
    - common
    - users

- name: Create user
  user:
    home=/home/{{ item }}
    name={{ item }}
    comment="{{ user[item]['comment'] }}"
    shell=/bin/bash
    uid={{ user[item]['uid'] }}
    groups="sudo,admin"
    state=present
  with_flattened: '{{admin_users}}'
  tags: 
    - common
    - users

- name: copy per-user ssh key (authorized_keys) to the destination server
  authorized_key:
    user={{ item }}
    key="{{ user[item]['key'] }}"
  with_flattened: '{{admin_users}}'
  tags: 
    - common
    - users


- name: add admin keys to authorized_keys of user ubuntu
  authorized_key: user=ubuntu
                  key="{{ user[item]['key'] }}"
  with_flattened: '{{ubuntu_keys}}'
  tags: 
    - common
    - users

- name: remove deleted user's key from authorized_keys of user ubuntu
  authorized_key:
    user=ubuntu
    key="{{ user[item]['key'] }}"
    state=absent
  with_flattened: '{{deleted_ubuntu_keys}}'
  tags: 
    - common
    - users


