---


- name: disable management of etc_hosts by cloud-init
  lineinfile: "dest=/etc/cloud/cloud.cfg.d/10_etc_hosts.cfg create=yes regexp='^\\s*manage_etc_hosts' line='manage_etc_hosts: False'"
  tags: 
    - common
  
- name: copy /etc/hosts
  template:
    src=hosts.j2
    dest=/etc/hosts
  tags:
    - common

