---

- name: logspout docker
  docker_container:
    name: logspout
    image: "{{logspout_docker_image}}"
    network_mode: host
    restart_policy: "unless-stopped"
    state: started
    pull: true
    env:
      ROUTE_URIS: "logstash://{{logstash_host}}:{{logstash_logspout_port}}"
      HTTP_PORT: "{{logspout_http_port}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  tags:
    - logspout
