---

- name: install packages
  apt:
    name: "docker.io"
    state: "present"
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"
  tags:
    - docker

- name: docker-py
  pip:
    name: "docker-py"
  tags:
    - docker
