---
# handles the web- & syncservers

- hosts: web,sync
#  gather_facts: no
  vars:
    node_type: web
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
  roles:
    - common
    - docker
    - maxscale
    - exim
    - nagios
    - role: owncloud
      tags: owncloud
    - ocphp_fpm
    - ocapache
    - filebeat
    - scripts
  become: true
