---
# handles the devservers


- hosts: dev
  vars:
    node_type: web
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
  roles:
    - common
    - role: docker_14_06
      tags: docker
    - maxscale
    - exim
    #- nagios
    - logstash_forwarder
    - role: owncloud
      tags: owncloud
    - ocphp_fpm
    - ocapache
    - scripts
    #- ocdev
  become: true

