---

- hosts: localhost
  vars:
    docker_registry: "docker.drive.switch.ch"
  roles:
    - logspout_image
    - maxscale_image
    - grafana_image
    - graphite_image
    - ocphp_fpm_image
    - ocapache_image
    - haproxy_image
    - curator_image
  become: true
  gather_facts: no
  environment:
     # if used on mac with docker toolbox instead of the newer docker for mac.
     DOCKER_TLS_VERIFY: "{{ lookup('env','DOCKER_TLS_VERIFY') }}"
     DOCKER_HOST: "{{ lookup('env','DOCKER_HOST') }}"
     DOCKER_CERT_PATH: "{{ lookup('env','DOCKER_CERT_PATH') }}"
     DOCKER_MACHINE_NAME: "{{ lookup('env','DOCKER_MACHINE_NAME') }}"
