---
# the database servers

- hosts: elk
  vars_files:
    - ../vars/users.yml
    #- ../vars/data-volumes.{{ volumes_inventory_name }}.yml
    - ../vars/servers.{{ site }}.yml
  roles:
    - data_volumes
    - common
    - docker
    - elasticsearch
    - kibana
    - logstash
    - filebeat
    - curator
  become: true
