---
# the database servers

- hosts: elk
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
  roles:
    - common
    - role: elk
      tags:
         - elk
  become: true

