---

- hosts:
    - mariadb
  gather_facts: no
  tasks:
    - setup:
  tags:
    - prometheus


- hosts: graphite
  vars_files:
    - '../vars/users.yml'
  roles:
    - ephemeral_disk
    - common
    - docker
    - grafana
    - graphite
    - prometheus
    - logspout
    - keepalived
  become: true
