---
# handles the loadbalancers

# in order to limit run with e.g: --limit=*.52,10.0.23.1*,10.0.23.2*,*6*,*17

- hosts: 
    - web
    - sync 
    - ldap
    - dev
  gather_facts: no
  tasks:
    - setup:
      tags:
        - config
        - haconfig
  become: true

- hosts: 
    - lb[0]
    #- 10.0.23.53
  vars:
    node_type: ha
  vars_files:
    - ../vars/users.yml
  roles:
    - common
    - nagios
    - haproxy
  become: true
