---

- hosts: mariadb
  vars_files:
    - ../vars/users.yml
  vars:
    node_type: mariadb
  roles:
    - common
    - ephemeral_disk
    - docker
    - logspout
    - scripts
    - nagios
    - mariadb
  become: true


- hosts: mariadb
  # one must not restart all instances at the same time!!!!
  serial: 1
  become: true
  vars_files:
    - ../vars/users.yml
  vars:
    node_type: mariadb
  roles:
    - mariadb_base
  post_tasks:
    - include: tasks/wait_for_mariadb.yml
