---

- hosts: mgmt
  #gather_facts: no
  become: true
  vars:
    node_type: web
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
    - ../vars/snapshots.yml
    - ../vars/servers.{{ site }}.yml
  roles:
    - common
    - docker
    - maxscale
    #- exim
    - role: owncloud
      tags: owncloud
    - ocphp_fpm
    # no apache, that way we make sure this will never become an active oc server.
    #- ocapache
    - filebeat
    - mgmt
    - openstack
    - scripts
