---

- hosts: mgmt
  #gather_facts: no
  become: true
  vars:
    node_type: web
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
  roles:
    - common
    - role: docker_14_06
      tags: docker
    - maxscale
    - exim
    - logstash_forwarder
    - owncloud
    - ocphp_fpm
    - ocapache
    - scripts
    - mgmt
