---

# the NSF servers

- hosts: dev
  tasks:
    - name: talk to web servers to populate facts
      command: /bin/true
  tags:
    - config
  become: true

- hosts: nfs
  vars:
        node_type: nfs
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
    - ../vars/servers.{{ site }}.yml
  roles:
    - data_volumes
    - common
    - nagios
    - nfs-server
    - scripts
  post_tasks:
    - name: create ocdata link
      file:
        dest: "/mnt/data/{{ item.name }}"
        src: "/mnt/{{ item.link }}/._ocdata"
        state: link
        force: yes
      with_items: "{{ocdata_links}}"
      delegate_to: "{{ hostvars[groups['nfs'][0]].inventory_hostname }}"
      tags:
        - ocdata
  become: true
