---
# handles the syncservers

- hosts: sync
#  gather_facts: no
  vars:
    node_type: web
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
  roles:
    - common
    - docker
    - maxscale
    - exim
    - nagios
    - logstash_forwarder
    - role: owncloud
      tags: owncloud
    - ocphp_fpm
    - ocapache
    - scripts
  become: true
