---
# handles the webservers

- hosts: web
  vars:
    node_type: web
    #php_ini_file: "php.xdebug.ini"
  vars_files:
    - ../vars/users.yml
    - ../vars/data-volumes.{{ volumes_inventory_name }}.yml
    - ../vars/servers.{{ site }}.yml
  roles:
    - common
    - docker
    - maxscale
    - exim
    - nagios
    - role: owncloud
      tags: owncloud
    - ocphp_fpm
    - ocapache
    - filebeat
    - scripts
  become: true
