---

- name: install authorized keys
  copy:
     src="../authorized_keys/{{service_name}}_nfs_root.pub"
     dest="/root/.ssh/authorized_keys"
     mode="0600"
  tags:
    - sshkeys
    
- name: install ssh key
  copy:
     content="{{ssh_private_key_nfs_root[service_name]}}"
     dest="/root/.ssh/id_rsa"
     mode="0600"
  tags:
    - sshkeys
  
